name: Build

on: [push, pull_request]

jobs:
  R_build_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest]
        r-version: ['4.4.1']
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::testthat
        working-directory: R/atlasapprox

    - name: Install package
      run: R CMD INSTALL R/atlasapprox

    - name: Run test with testthat
      working-directory: R
      run: |
        Rscript -e '
          library(testthat)
          library(atlasapprox)
          test_dir("tests/testthat", reporter = "progress")
        '